modLoader="javafml"
loaderVersion="[2,)"
license="MIT"
[[mods]]
modId="trueeconomy"
version="1.21"
displayName="True-Economy"
description="Dynamic supply/demand economy, black market, shops, auctions, banking and more."
