plugins {
    id 'fabric-loom'
    id 'java'
}

version = "1.19"
group = 'com.economy.mod'

dependencies {
    minecraft "com.mojang.minecraft:minecraft:1.19"
    mappings "net.fabricmc:yarn:1.19+build.4"
    modImplementation "net.fabricmc:fabric-loader:0.19.5"
    modImplementation "net.fabricmc.fabric-api:fabric-api:0.58.0+1.19"
    implementation project(':core')
    include project(':core')
    implementation 'com.google.code.gson:gson:2.11.0'
    include 'com.google.code.gson:gson:2.11.0'
}

sourceSets {
    main {
        java.srcDirs += project.file('../../glue/src/main/java')
    }
}

java {
    withSourcesJar()
}


processResources {
    inputs.property('modEnvironment', project.findProperty('modEnvironment') ?: '*')
    filesMatching('*.mod.json') { expand(modEnvironment: project.findProperty('modEnvironment') ?: '*') }
}

tasks.withType(JavaCompile) { options.encoding = 'UTF-8' }
