modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
[[mods]]
modId="trueeconomy"
version="1.20.1"
displayName="True-Economy"
description="Dynamic supply/demand economy, black market, shops, auctions, banking and more."
