modLoader="javafml"
loaderVersion="[45,)"
license="MIT"
[[mods]]
modId="trueeconomy"
version="1.19.4"
displayName="True-Economy"
description="Dynamic supply/demand economy, black market, shops, auctions, banking and more."
